[package]
name = "cardinal"
version = "0.1.0"
authors = ["Tyler Philbrick <tyler@tylerphilbrick.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = "0.8.2"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]
