[package]
name = "cardinal"
version = "0.1.0"
authors = ["Tyler Philbrick <tyler@tylerphilbrick.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
opt-level = "s"

[dependencies]
multiboot2 = "0.10"
spin = "0.7"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
